# This is a basic workflow to help you get started with Actions

name: Continuos

# Controls when the workflow will run
on: 
  workflow_dispatch:

jobs:  
  build:    
    runs-on: ubuntu-latest    
    steps:      
      - name: Run a one-line script
        run: echo Hello, world!
  deploy-dev:   
    runs-on: ubuntu-latest
    environment: dev
    name: dev
    steps:      
      - name: deploy dev
        run: echo deployed in dev !
  deploy-hmg:   
    runs-on: ubuntu-latest
    environment: hmg
    name: hmg
    steps:      
      - name: deploy hmg
        run: echo deployed in 
