# This is a basic workflow to help you get started with Actions

name: CI
on: 
  workflow_dispatch:
  
jobs:  
  build:    
    runs-on: ubuntu-latest    
    steps:      
      - name: Run a one-line script
        run: echo Hello, world!
  deploy-dev:   
    runs-on: ubuntu-latest
    environment: dev
    name: development
    needs: build
    steps:      
      - name: deploy development
        run: echo deployed in development !
        
  deploy-hmg:   
    runs-on: ubuntu-latest
    environment: hmg
    name: homologation
    needs: deploy-dev
    steps:      
      - name: deploy homologation
        run: echo deployed in homologation !
